name: Manual Test Suite

on:
  workflow_dispatch:
    inputs:
      test_case:
        description: 'Choose Test Case'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - test_case_5_and_6

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager
          pip install pylance

      - name: Run Full Set of Tests
        if: ${{ inputs.test_case == 'full' }}
        run: |
          python -m unittest discover -s tests


